language: node_js
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      node_js: "8" # to be removed on "December 2019"
    - os: osx
      node_js: "8" # to be removed on "December 2019"
    - os: linux
      dist: trusty
      sudo: required
      node_js: "10" # to be removed on "April 2021"
    - os: linux
      dist: trusty
      sudo: required
      node_js: "12" # to be removed on "April 2022"
addons:
  chrome: stable
  firefox: latest
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CHROME_BIN=google-chrome-stable; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
script:
  - npm test
